version: '1.0'
name: lenovo-shop-ci
displayName: 京东云自动部署流水线
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - happy-end
      precise:
        - happy-end2
stages:
  - name: build_stage
    displayName: 构建阶段
    strategy: naturally
    trigger: auto
    executor:
      - yvi-ksm
      - anyeling
    steps:
      - step: shell@agent
        name: deploy_task
        displayName: 执行部署任务
        hostGroupID:
          ID: 京东云
          hostID:
            - 25214072-8149-4497-aec9-e930cbc1f759
        scriptType: SH
        script:
          - cd /root/lenovo-shop-ci/lenovo-shop
          - ''
          - git fetch --all
          - ''
          - git reset --hard origin/$GITEE_BRANCH
          - ''
          - chmod +x /root/lenovo-shop-ci/deploy.sh
          - ''
          - sh /root/lenovo-shop-ci/deploy.sh
        strategy: {}
strategy:
  blocking: false
